
# synthetic_topological_audit_pipeline.py
# -*- coding: utf-8 -*-
"""
Topological Auditing of Synthetic Public Data for Trustworthy Governance
========================================================================

This script implements an end-to-end, reproducible auditing pipeline for releasing
synthetic public datasets with (i) quantified analytical utility, (ii) quantified
privacy risk under explicit threat models, and (iii) quantified structural fidelity
beyond marginals, including topology-aware auditing in a shared representation space.

Design intent (mapping to the chapter structure):
  * Section 5.1 (Experimental Design): dataset profiling, governance scope, evaluation splits,
    and adversary assumptions.
  * Section 5.2 (Utility–Privacy Trade-Offs): fidelity metrics, downstream task transfer,
    fairness diagnostics, and privacy risk curves.
  * Section 5.3 (Topological Auditing Outcomes): persistence summaries, diagram distances,
    subgroup integrity checks, and temporal-window checks (when a time column is provided).

The pipeline operationalizes the theoretical and methodological principles described in the
uploaded documents: generator portfolios + replica strategy, utility layers (statistical
fidelity + task fidelity), attack-style privacy testing, and topology-aware structural auditing.

Requirements (typical):
  - Python 3.9+
  - numpy, pandas, matplotlib, scipy, scikit-learn, torch

Run:
  python synthetic_topological_audit_pipeline.py --data_path PATH/TO/DATA.csv --target TARGET_COL \
      --group_col GROUP_COL --time_col TIME_COL --output_dir results

If --data_path is omitted, a small mixed-type demo dataset is generated to validate the pipeline.

Outputs:
  results/<run_id>/
      5_1_experimental_design/
      5_2_utility_privacy_tradeoffs/
      5_3_topological_auditing/

Author: (generated by ChatGPT)
"""

from __future__ import annotations

import argparse
import dataclasses
import datetime as _dt
import json
import math
import os
import random
import shutil
import sys
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from scipy import stats
from scipy.spatial.distance import cdist, pdist, squareform
from scipy.optimize import linear_sum_assignment

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    f1_score,
    accuracy_score,
    precision_score,
    recall_score,
    confusion_matrix,
    roc_curve,
)
from sklearn.model_selection import train_test_split
from sklearn.neighbors import NearestNeighbors
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression, Ridge
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset


# =============================================================================
# Reproducibility utilities
# =============================================================================

def set_global_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def now_run_id() -> str:
    return _dt.datetime.now().strftime("run_%Y%m%d_%H%M%S")


def save_json(obj: Dict[str, Any], path: str) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2, ensure_ascii=False)


def save_text(text: str, path: str) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def save_df(df: pd.DataFrame, path: str) -> None:
    df.to_csv(path, index=False, encoding="utf-8")


def fig_save_close(fig: plt.Figure, path: str, dpi: int = 160) -> None:
    fig.tight_layout()
    fig.savefig(path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


# =============================================================================
# Configuration objects (governance + evaluation + generators)
# =============================================================================

@dataclass
class GovernanceScope:
    sensitivity_tier: str = "Tier-2 (moderate sensitivity)"
    sharing_scope: str = "Controlled access (accredited researchers / inter-agency)"
    legal_constraints: str = "Policy-dependent; document and review per dataset."
    intended_use_cases: List[str] = dataclasses.field(
        default_factory=lambda: [
            "Policy analytics (classification/regression on program outcomes)",
            "Monitoring and anomaly screening",
            "Subgroup comparisons (fairness / representational adequacy)",
            "Temporal regime analysis (if time-indexed)",
        ]
    )


@dataclass
class ThreatModel:
    attacker_interface: str = "Black-box attacker with access to released synthetic data"
    attacker_auxiliary_info: str = "Partial quasi-identifiers + public registries (simulated)"
    attacks_considered: List[str] = dataclasses.field(
        default_factory=lambda: [
            "Membership inference (distance-based proxy)",
            "Attribute inference (synthetic-trained predictor)",
            "Linkage / uniqueness risk (quasi-ID matching simulation)",
        ]
    )
    membership_attack_feature: str = "Nearest-neighbor distance to synthetic cloud"
    linkage_radius_quantile: float = 0.05  # radius is set to this quantile of NN distances


@dataclass
class EvaluationConfig:
    test_size: float = 0.25
    random_state: int = 42
    temporal_split: bool = False
    time_col: Optional[str] = None
    # Downstream task
    target_col: Optional[str] = None
    task_type: str = "auto"  # auto | classification | regression
    # Fairness
    group_col: Optional[str] = None
    sensitive_col: Optional[str] = None
    quasi_id_cols: List[str] = dataclasses.field(default_factory=list)


@dataclass
class GeneratorConfig:
    generators: List[str] = dataclasses.field(default_factory=lambda: ["bootstrap", "copula", "vae"])
    replicas: int = 3
    base_seed: int = 2026
    # bootstrap
    bootstrap_noise_scale: float = 0.05
    # VAE
    vae_latent_dim: int = 16
    vae_hidden_dim: int = 128
    vae_epochs: int = 35
    vae_batch_size: int = 256
    vae_lr: float = 1e-3
    vae_beta: float = 0.5  # KL weight
    vae_max_train_rows: int = 6000  # subsample cap for neural training


@dataclass
class TopologyConfig:
    embedding_dim: int = 8
    ae_hidden_dim: int = 128
    ae_epochs: int = 30
    ae_batch_size: int = 256
    ae_lr: float = 1e-3
    ae_max_train_rows: int = 8000  # subsample cap for embedding training
    # persistent homology
    subsample_n: int = 120
    rips_max_dim: int = 1  # compute H0 and H1 via triangles
    betti_grid_size: int = 60
    max_points_for_rips: int = 140  # safety


@dataclass
class AcceptanceConfig:
    # Conservative thresholds: adjustable per governance committee
    min_task_transfer_ratio: float = 0.90   # synthetic-task / real-task baseline
    max_membership_advantage: float = 0.20
    max_linkage_uniqueness: float = 0.10
    max_topology_distance: float = 0.35


@dataclass
class RunConfig:
    governance: GovernanceScope = dataclasses.field(default_factory=GovernanceScope)
    threat: ThreatModel = dataclasses.field(default_factory=ThreatModel)
    evaluation: EvaluationConfig = dataclasses.field(default_factory=EvaluationConfig)
    generators: GeneratorConfig = dataclasses.field(default_factory=GeneratorConfig)
    topology: TopologyConfig = dataclasses.field(default_factory=TopologyConfig)
    acceptance: AcceptanceConfig = dataclasses.field(default_factory=AcceptanceConfig)
    output_root: str = "results"
    run_id: str = dataclasses.field(default_factory=now_run_id)


# =============================================================================
# Data typing and preprocessing (mixed tabular)
# =============================================================================

def infer_column_types(df: pd.DataFrame, time_col: Optional[str], target_col: Optional[str]) -> Dict[str, List[str]]:
    numeric_cols: List[str] = []
    categorical_cols: List[str] = []
    boolean_cols: List[str] = []
    datetime_cols: List[str] = []

    for c in df.columns:
        if c == target_col:
            continue
        if time_col is not None and c == time_col:
            datetime_cols.append(c)
            continue

        s = df[c]
        if pd.api.types.is_bool_dtype(s):
            boolean_cols.append(c)
        elif pd.api.types.is_numeric_dtype(s):
            numeric_cols.append(c)
        elif pd.api.types.is_datetime64_any_dtype(s):
            datetime_cols.append(c)
        else:
            # Heuristic: small-cardinality numeric-looking object is still categorical
            categorical_cols.append(c)

    return {
        "numeric": numeric_cols,
        "categorical": categorical_cols,
        "boolean": boolean_cols,
        "datetime": datetime_cols,
    }


class MixedTabularPreprocessor:
    """
    Produces:
      - X_model: numpy array for sklearn models (numeric scaled + one-hot)
      - X_tensor: torch tensor for neural generators/embeddings
      - Inverse transform back to DataFrame for synthetic samples
    """

    def __init__(self, numeric_cols: List[str], categorical_cols: List[str], boolean_cols: List[str]):
        self.numeric_cols = list(numeric_cols)
        self.categorical_cols = list(categorical_cols)
        self.boolean_cols = list(boolean_cols)

        self.numeric_pipe = Pipeline(
            steps=[
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler()),
            ]
        )
        self.cat_pipe = Pipeline(
            steps=[
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
            ]
        )
        # treat booleans as categorical for stability
        self.bool_pipe = Pipeline(
            steps=[
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
            ]
        )

        transformers = []
        if self.numeric_cols:
            transformers.append(("num", self.numeric_pipe, self.numeric_cols))
        if self.categorical_cols:
            transformers.append(("cat", self.cat_pipe, self.categorical_cols))
        if self.boolean_cols:
            transformers.append(("bool", self.bool_pipe, self.boolean_cols))

        self.ct = ColumnTransformer(transformers=transformers, remainder="drop")
        self._fitted = False

        # for inverse mapping
        self._cat_categories: Dict[str, List[Any]] = {}
        self._bool_categories: Dict[str, List[Any]] = {}
        self._onehot_slices: Dict[str, Tuple[int, int]] = {}
        self._feature_names: List[str] = []
        self._numeric_scaler: Optional[StandardScaler] = None

    def fit(self, df: pd.DataFrame) -> "MixedTabularPreprocessor":
        self.ct.fit(df)
        self._fitted = True

        self._feature_names = list(self.ct.get_feature_names_out())

        # Extract scalers and categories
        if self.numeric_cols:
            num_pipe: Pipeline = self.ct.named_transformers_["num"]
            self._numeric_scaler = num_pipe.named_steps["scaler"]

        start = 0
        # numeric slice first if exists
        if self.numeric_cols:
            end = start + len(self.numeric_cols)
            start = end

        if self.categorical_cols:
            cat_pipe: Pipeline = self.ct.named_transformers_["cat"]
            ohe: OneHotEncoder = cat_pipe.named_steps["onehot"]
            cats = ohe.categories_
            # compute slices for each categorical col
            idx = start
            for col, cat_list in zip(self.categorical_cols, cats):
                k = len(cat_list)
                self._cat_categories[col] = list(cat_list)
                self._onehot_slices[col] = (idx, idx + k)
                idx += k
            start = idx

        if self.boolean_cols:
            bool_pipe: Pipeline = self.ct.named_transformers_["bool"]
            ohe: OneHotEncoder = bool_pipe.named_steps["onehot"]
            cats = ohe.categories_
            idx = start
            for col, cat_list in zip(self.boolean_cols, cats):
                k = len(cat_list)
                self._bool_categories[col] = list(cat_list)
                self._onehot_slices[col] = (idx, idx + k)
                idx += k

        return self

    def transform(self, df: pd.DataFrame) -> np.ndarray:
        if not self._fitted:
            raise RuntimeError("Preprocessor must be fitted before transform.")
        X = self.ct.transform(df)
        return np.asarray(X, dtype=np.float32)

    def transform_tensor(self, df: pd.DataFrame, device: torch.device) -> torch.Tensor:
        X = self.transform(df)
        return torch.from_numpy(X).to(device)

    def inverse_samples(self, X: np.ndarray, reference_df: pd.DataFrame) -> pd.DataFrame:
        """
        Approximate inverse transform:
          - numeric: inverse StandardScaler then clip to observed min/max in reference_df
          - categorical/bool: argmax over one-hot block
        """
        if not self._fitted:
            raise RuntimeError("Preprocessor must be fitted before inverse_samples.")

        X = np.asarray(X, dtype=np.float32)
        out: Dict[str, Any] = {}

        # Numeric
        offset = 0
        if self.numeric_cols:
            num_scaled = X[:, : len(self.numeric_cols)]
            scaler = self._numeric_scaler
            assert scaler is not None
            num = scaler.inverse_transform(num_scaled)
            for i, col in enumerate(self.numeric_cols):
                col_min = pd.to_numeric(reference_df[col], errors="coerce").min()
                col_max = pd.to_numeric(reference_df[col], errors="coerce").max()
                v = np.clip(num[:, i], col_min, col_max)
                # try to preserve integers if original looks integer-like
                if pd.api.types.is_integer_dtype(reference_df[col]) or (reference_df[col].dropna().apply(float.is_integer).mean() > 0.95):
                    v = np.round(v).astype(int)
                out[col] = v
            offset = len(self.numeric_cols)

        # Categorical + Boolean
        for col in (self.categorical_cols + self.boolean_cols):
            a, b = self._onehot_slices[col]
            block = X[:, a:b]
            idx = np.argmax(block, axis=1)
            if col in self._cat_categories:
                cats = self._cat_categories[col]
            else:
                cats = self._bool_categories[col]
            out[col] = [cats[int(i)] for i in idx]

        return pd.DataFrame(out)


# =============================================================================
# Generator portfolio
# =============================================================================

class BaseGenerator:
    name: str = "base"

    def fit(self, df_train: pd.DataFrame, pre: MixedTabularPreprocessor, config: RunConfig) -> "BaseGenerator":
        raise NotImplementedError

    def sample(self, n: int, seed: int) -> pd.DataFrame:
        raise NotImplementedError


class BootstrapNoiseGenerator(BaseGenerator):
    name = "bootstrap"

    def __init__(self, numeric_cols: List[str], noise_scale: float):
        self.numeric_cols = numeric_cols
        self.noise_scale = noise_scale
        self.df_train: Optional[pd.DataFrame] = None
        self._num_std: Optional[pd.Series] = None

    def fit(self, df_train: pd.DataFrame, pre: MixedTabularPreprocessor, config: RunConfig) -> "BootstrapNoiseGenerator":
        self.df_train = df_train.reset_index(drop=True).copy()
        if self.numeric_cols:
            self._num_std = self.df_train[self.numeric_cols].astype(float).std(ddof=0).replace(0.0, 1.0)
        return self

    def sample(self, n: int, seed: int) -> pd.DataFrame:
        assert self.df_train is not None
        rng = np.random.default_rng(seed)
        idx = rng.integers(0, len(self.df_train), size=n)
        syn = self.df_train.iloc[idx].copy().reset_index(drop=True)
        if self.numeric_cols:
            std = self._num_std
            assert std is not None
            noise = rng.normal(0.0, 1.0, size=(n, len(self.numeric_cols))) * (std.values * self.noise_scale)
            syn[self.numeric_cols] = syn[self.numeric_cols].astype(float).values + noise
            # clip to observed bounds
            for col in self.numeric_cols:
                col_min = pd.to_numeric(self.df_train[col], errors="coerce").min()
                col_max = pd.to_numeric(self.df_train[col], errors="coerce").max()
                syn[col] = syn[col].clip(col_min, col_max)
        return syn


class GaussianCopulaGenerator(BaseGenerator):
    name = "copula"

    def __init__(self, numeric_cols: List[str], categorical_cols: List[str], boolean_cols: List[str]):
        self.numeric_cols = numeric_cols
        self.categorical_cols = categorical_cols
        self.boolean_cols = boolean_cols

        self.df_train: Optional[pd.DataFrame] = None
        self._corr: Optional[np.ndarray] = None
        self._num_quantiles: Dict[str, Tuple[np.ndarray, np.ndarray]] = {}
        self._cat_freq: Dict[str, Tuple[np.ndarray, np.ndarray]] = {}
        self._bool_freq: Dict[str, Tuple[np.ndarray, np.ndarray]] = {}

    @staticmethod
    def _rank_to_normal(x: np.ndarray) -> np.ndarray:
        r = stats.rankdata(x, method="average")
        u = (r - 0.5) / len(x)
        return stats.norm.ppf(u)

    def fit(self, df_train: pd.DataFrame, pre: MixedTabularPreprocessor, config: RunConfig) -> "GaussianCopulaGenerator":
        self.df_train = df_train.reset_index(drop=True).copy()

        # numeric copula fit
        if self.numeric_cols:
            Z = []
            for col in self.numeric_cols:
                x = pd.to_numeric(self.df_train[col], errors="coerce").to_numpy()
                x = np.nan_to_num(x, nan=np.nanmedian(x))
                z = self._rank_to_normal(x)
                Z.append(z)
                # store inverse empirical CDF via quantiles
                qs = np.linspace(0.0, 1.0, 1001)
                vals = np.quantile(x, qs)
                self._num_quantiles[col] = (qs, vals)
            Z = np.vstack(Z).T
            self._corr = np.corrcoef(Z, rowvar=False)
            # numerical stability
            self._corr = np.nan_to_num(self._corr, nan=0.0)
            self._corr = (self._corr + self._corr.T) / 2.0
            np.fill_diagonal(self._corr, 1.0)

        # categorical + boolean fit: empirical frequencies
        for col in self.categorical_cols:
            vc = self.df_train[col].astype(str).fillna("MISSING").value_counts(dropna=False)
            values = vc.index.to_numpy()
            probs = (vc / vc.sum()).to_numpy()
            self._cat_freq[col] = (values, probs)

        for col in self.boolean_cols:
            vc = self.df_train[col].astype(str).fillna("MISSING").value_counts(dropna=False)
            values = vc.index.to_numpy()
            probs = (vc / vc.sum()).to_numpy()
            self._bool_freq[col] = (values, probs)

        return self

    def sample(self, n: int, seed: int) -> pd.DataFrame:
        assert self.df_train is not None
        rng = np.random.default_rng(seed)
        out: Dict[str, Any] = {}

        # numeric
        if self.numeric_cols:
            corr = self._corr
            assert corr is not None
            # sample multivariate normal
            L = np.linalg.cholesky(corr + 1e-6 * np.eye(len(self.numeric_cols)))
            Z = rng.normal(size=(n, len(self.numeric_cols))) @ L.T
            U = stats.norm.cdf(Z)
            for j, col in enumerate(self.numeric_cols):
                qs, vals = self._num_quantiles[col]
                u = np.clip(U[:, j], 0.0, 1.0)
                out[col] = np.interp(u, qs, vals)

            # clip and round integer-like columns
            for col in self.numeric_cols:
                col_min = pd.to_numeric(self.df_train[col], errors="coerce").min()
                col_max = pd.to_numeric(self.df_train[col], errors="coerce").max()
                v = np.clip(out[col], col_min, col_max)
                if pd.api.types.is_integer_dtype(self.df_train[col]) or (self.df_train[col].dropna().apply(float.is_integer).mean() > 0.95):
                    v = np.round(v).astype(int)
                out[col] = v

        # categorical + boolean
        for col, (values, probs) in self._cat_freq.items():
            out[col] = rng.choice(values, size=n, replace=True, p=probs)

        for col, (values, probs) in self._bool_freq.items():
            out[col] = rng.choice(values, size=n, replace=True, p=probs)

        return pd.DataFrame(out)


class TabularVAE(nn.Module):
    def __init__(self, input_dim: int, latent_dim: int, hidden_dim: int):
        super().__init__()
        self.enc1 = nn.Linear(input_dim, hidden_dim)
        self.enc2 = nn.Linear(hidden_dim, hidden_dim)
        self.mu = nn.Linear(hidden_dim, latent_dim)
        self.logvar = nn.Linear(hidden_dim, latent_dim)

        self.dec1 = nn.Linear(latent_dim, hidden_dim)
        self.dec2 = nn.Linear(hidden_dim, hidden_dim)
        self.out = nn.Linear(hidden_dim, input_dim)

    def encode(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        h = F.relu(self.enc1(x))
        h = F.relu(self.enc2(h))
        return self.mu(h), self.logvar(h)

    def reparameterize(self, mu: torch.Tensor, logvar: torch.Tensor) -> torch.Tensor:
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def decode(self, z: torch.Tensor) -> torch.Tensor:
        h = F.relu(self.dec1(z))
        h = F.relu(self.dec2(h))
        return self.out(h)

    def forward(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        mu, logvar = self.encode(x)
        z = self.reparameterize(mu, logvar)
        recon = self.decode(z)
        return recon, mu, logvar


class VAEGenerator(BaseGenerator):
    name = "vae"

    def __init__(self, pre: MixedTabularPreprocessor, cfg: GeneratorConfig, device: torch.device):
        self.pre = pre
        self.cfg = cfg
        self.device = device
        self.model: Optional[TabularVAE] = None
        self.reference_df: Optional[pd.DataFrame] = None

    def fit(self, df_train: pd.DataFrame, pre: MixedTabularPreprocessor, config: RunConfig) -> "VAEGenerator":
        self.reference_df = df_train.copy()
        X = self.pre.transform(df_train)
        # Subsample to keep training feasible for large datasets (governance-friendly evaluation budgets)
        if X.shape[0] > self.cfg.vae_max_train_rows:
            rng = np.random.default_rng(12345)
            idx = rng.choice(X.shape[0], size=self.cfg.vae_max_train_rows, replace=False)
            X = X[idx]
        X_t = torch.from_numpy(X).to(self.device)

        ds = TensorDataset(X_t)
        dl = DataLoader(ds, batch_size=self.cfg.vae_batch_size, shuffle=True, drop_last=False)

        model = TabularVAE(input_dim=X.shape[1], latent_dim=self.cfg.vae_latent_dim, hidden_dim=self.cfg.vae_hidden_dim).to(self.device)
        opt = torch.optim.Adam(model.parameters(), lr=self.cfg.vae_lr)

        model.train()
        for epoch in range(1, self.cfg.vae_epochs + 1):
            losses = []
            for (xb,) in dl:
                opt.zero_grad()
                recon, mu, logvar = model(xb)
                # reconstruction loss: MSE on full vector (scaled numeric + one-hot)
                rec_loss = F.mse_loss(recon, xb, reduction="mean")
                kl = -0.5 * torch.mean(1 + logvar - mu.pow(2) - logvar.exp())
                loss = rec_loss + self.cfg.vae_beta * kl
                loss.backward()
                opt.step()
                losses.append(float(loss.detach().cpu().item()))
            # minimal verbosity: keep last
        self.model = model
        return self

    def sample(self, n: int, seed: int) -> pd.DataFrame:
        if self.model is None or self.reference_df is None:
            raise RuntimeError("VAEGenerator must be fitted before sampling.")
        set_global_seed(seed)
        self.model.eval()
        with torch.no_grad():
            z = torch.randn((n, self.cfg.vae_latent_dim), device=self.device)
            x_hat = self.model.decode(z).cpu().numpy()
        # inverse to dataframe
        syn = self.pre.inverse_samples(x_hat, reference_df=self.reference_df)
        return syn


# =============================================================================
# Utility metrics (statistical fidelity + downstream transfer + fairness)
# =============================================================================

def rbf_mmd2(X: np.ndarray, Y: np.ndarray, gamma: Optional[float] = None, max_points: int = 500, seed: int = 0) -> float:
    """
    Squared MMD with RBF kernel. Subsamples to control O(n^2) cost.
    """
    rng = np.random.default_rng(seed)
    if X.shape[0] > max_points:
        X = X[rng.choice(X.shape[0], size=max_points, replace=False)]
    if Y.shape[0] > max_points:
        Y = Y[rng.choice(Y.shape[0], size=max_points, replace=False)]

    # median heuristic if gamma missing
    if gamma is None:
        Z = np.vstack([X, Y])
        if Z.shape[0] > 2 * max_points:
            Z = Z[rng.choice(Z.shape[0], size=2 * max_points, replace=False)]
        dists = pdist(Z, metric="euclidean")
        med = np.median(dists)
        gamma = 1.0 / (2.0 * med * med + 1e-12)

    def k(a: np.ndarray, b: np.ndarray) -> np.ndarray:
        D = cdist(a, b, metric="sqeuclidean")
        return np.exp(-gamma * D)

    Kxx = k(X, X)
    Kyy = k(Y, Y)
    Kxy = k(X, Y)

    m = X.shape[0]
    n = Y.shape[0]

    # unbiased estimate
    mmd2 = (Kxx.sum() - np.trace(Kxx)) / (m * (m - 1) + 1e-12) \
         + (Kyy.sum() - np.trace(Kyy)) / (n * (n - 1) + 1e-12) \
         - 2.0 * Kxy.mean()
    return float(max(mmd2, 0.0))


def jensen_shannon_divergence(p: np.ndarray, q: np.ndarray) -> float:
    p = np.asarray(p, dtype=float)
    q = np.asarray(q, dtype=float)
    p = p / (p.sum() + 1e-12)
    q = q / (q.sum() + 1e-12)
    m = 0.5 * (p + q)
    return 0.5 * (stats.entropy(p, m) + stats.entropy(q, m))


def compute_fidelity_metrics(df_real: pd.DataFrame, df_syn: pd.DataFrame, numeric_cols: List[str], categorical_cols: List[str], boolean_cols: List[str]) -> Dict[str, float]:
    metrics: Dict[str, float] = {}

    # numeric: Wasserstein distance per column
    wass = []
    for col in numeric_cols:
        a = pd.to_numeric(df_real[col], errors="coerce").dropna().to_numpy()
        b = pd.to_numeric(df_syn[col], errors="coerce").dropna().to_numpy()
        if len(a) == 0 or len(b) == 0:
            continue
        w = stats.wasserstein_distance(a, b)
        # normalize by real std to make columns comparable
        s = np.std(a) + 1e-12
        wass.append(w / s)
    metrics["numeric_wasserstein_mean"] = float(np.mean(wass) if wass else np.nan)

    # categorical/boolean: JS divergence per column
    js = []
    for col in (categorical_cols + boolean_cols):
        a = df_real[col].astype(str).fillna("MISSING")
        b = df_syn[col].astype(str).fillna("MISSING")
        cats = sorted(set(a.unique()).union(set(b.unique())))
        pa = np.array([(a == c).mean() for c in cats], dtype=float)
        pb = np.array([(b == c).mean() for c in cats], dtype=float)
        js.append(jensen_shannon_divergence(pa, pb))
    metrics["categorical_js_mean"] = float(np.mean(js) if js else np.nan)

    # correlation gap (numeric-numeric Spearman)
    if len(numeric_cols) >= 2:
        R1 = df_real[numeric_cols].astype(float).corr(method="spearman").to_numpy()
        R2 = df_syn[numeric_cols].astype(float).corr(method="spearman").to_numpy()
        gap = np.nanmean(np.abs(R1 - R2))
        metrics["spearman_corr_gap_mean"] = float(gap)
    else:
        metrics["spearman_corr_gap_mean"] = np.nan

    return metrics


def infer_task_type(y: pd.Series) -> str:
    if pd.api.types.is_numeric_dtype(y):
        # heuristic: small number of unique values -> classification
        uniq = y.dropna().unique()
        if len(uniq) <= 20 and set(map(float, uniq)) <= set(map(float, range(int(max(uniq)) + 1))):
            return "classification"
        return "regression"
    return "classification"


def train_eval_downstream(
    X_train: np.ndarray,
    y_train: np.ndarray,
    X_test: np.ndarray,
    y_test: np.ndarray,
    task_type: str,
    seed: int,
) -> Dict[str, float]:
    """
    A compact but governance-relevant benchmark:
      - Classification: LogisticRegression + RandomForest; report ROC-AUC (if binary) and macro-F1.
      - Regression: Ridge + RandomForestRegressor; report RMSE and R2.
    """
    out: Dict[str, float] = {}
    if task_type == "classification":
        # determine binary vs multiclass
        classes = np.unique(y_train[~pd.isna(y_train)])
        is_binary = len(classes) == 2

        # Logistic regression
        lr = LogisticRegression(max_iter=2000, n_jobs=None, random_state=seed)
        lr.fit(X_train, y_train)
        pred = lr.predict(X_test)
        out["lr_macro_f1"] = float(f1_score(y_test, pred, average="macro"))
        if is_binary:
            proba = lr.predict_proba(X_test)[:, 1]
            out["lr_roc_auc"] = float(roc_auc_score(y_test, proba))
            out["lr_avg_precision"] = float(average_precision_score(y_test, proba))
        else:
            out["lr_roc_auc"] = np.nan
            out["lr_avg_precision"] = np.nan

        # Random forest
        rf = RandomForestClassifier(n_estimators=250, random_state=seed, n_jobs=-1)
        rf.fit(X_train, y_train)
        pred = rf.predict(X_test)
        out["rf_macro_f1"] = float(f1_score(y_test, pred, average="macro"))
        if is_binary:
            proba = rf.predict_proba(X_test)[:, 1]
            out["rf_roc_auc"] = float(roc_auc_score(y_test, proba))
            out["rf_avg_precision"] = float(average_precision_score(y_test, proba))
        else:
            out["rf_roc_auc"] = np.nan
            out["rf_avg_precision"] = np.nan

    else:
        # Ridge regression
        rr = Ridge(alpha=1.0, random_state=seed)
        rr.fit(X_train, y_train)
        pred = rr.predict(X_test)
        rmse = float(np.sqrt(np.mean((pred - y_test) ** 2)))
        out["ridge_rmse"] = rmse
        # R2
        ss_res = float(np.sum((y_test - pred) ** 2))
        ss_tot = float(np.sum((y_test - np.mean(y_test)) ** 2) + 1e-12)
        out["ridge_r2"] = float(1.0 - ss_res / ss_tot)

        # Random forest regressor
        rf = RandomForestRegressor(n_estimators=300, random_state=seed, n_jobs=-1)
        rf.fit(X_train, y_train)
        pred = rf.predict(X_test)
        rmse = float(np.sqrt(np.mean((pred - y_test) ** 2)))
        out["rf_rmse"] = rmse
        ss_res = float(np.sum((y_test - pred) ** 2))
        ss_tot = float(np.sum((y_test - np.mean(y_test)) ** 2) + 1e-12)
        out["rf_r2"] = float(1.0 - ss_res / ss_tot)

    return out


def fairness_diagnostics_binary(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    group: np.ndarray,
) -> pd.DataFrame:
    """
    Computes per-group confusion rates (binary only). Returns a table with:
      - support
      - TPR, FPR, precision, recall, F1
    """
    rows = []
    groups = pd.Series(group).astype(str).unique()
    for g in sorted(groups):
        m = (pd.Series(group).astype(str) == g).to_numpy()
        yt = y_true[m]
        yp = y_pred[m]
        if len(yt) == 0:
            continue
        tn, fp, fn, tp = confusion_matrix(yt, yp, labels=[0, 1]).ravel()
        tpr = tp / (tp + fn + 1e-12)
        fpr = fp / (fp + tn + 1e-12)
        prec = tp / (tp + fp + 1e-12)
        rec = tpr
        f1 = 2 * prec * rec / (prec + rec + 1e-12)
        rows.append(
            {
                "group": g,
                "support": int(len(yt)),
                "TPR": float(tpr),
                "FPR": float(fpr),
                "precision": float(prec),
                "recall": float(rec),
                "F1": float(f1),
            }
        )
    return pd.DataFrame(rows)


# =============================================================================
# Privacy risk: membership, attribute, linkage
# =============================================================================

def membership_inference_attack(
    X_members: np.ndarray,
    X_nonmembers: np.ndarray,
    X_syn: np.ndarray,
    seed: int,
) -> Dict[str, Any]:
    """
    Distance-based membership inference proxy:
      score(x) = -min_{s in S_syn} ||x - s||_2
    Attack AUC and advantage = max(TPR - FPR).
    """
    nn = NearestNeighbors(n_neighbors=1, algorithm="auto").fit(X_syn)
    d_mem, _ = nn.kneighbors(X_members, n_neighbors=1, return_distance=True)
    d_non, _ = nn.kneighbors(X_nonmembers, n_neighbors=1, return_distance=True)
    scores = np.concatenate([-d_mem.ravel(), -d_non.ravel()], axis=0)
    labels = np.concatenate([np.ones(len(d_mem)), np.zeros(len(d_non))], axis=0)

    auc = roc_auc_score(labels, scores)
    fpr, tpr, thr = roc_curve(labels, scores)
    adv = float(np.max(tpr - fpr))
    return {
        "membership_auc": float(auc),
        "membership_advantage": float(adv),
        "roc_fpr": fpr.tolist(),
        "roc_tpr": tpr.tolist(),
        "roc_thr": thr.tolist(),
    }


def attribute_inference_risk(
    df_syn: pd.DataFrame,
    df_real_test: pd.DataFrame,
    sensitive_col: str,
    feature_cols: List[str],
    seed: int,
) -> Dict[str, float]:
    """
    Attacker trains a predictor of the sensitive attribute using synthetic data.
    Risk is the improvement over a naive baseline (majority class or mean).
    """
    y_syn = df_syn[sensitive_col]
    X_syn = df_syn[feature_cols]
    y_test = df_real_test[sensitive_col]
    X_test = df_real_test[feature_cols]

    # handle missing
    X_syn = X_syn.copy()
    X_test = X_test.copy()
    for c in feature_cols:
        if pd.api.types.is_numeric_dtype(X_syn[c]):
            med = pd.to_numeric(X_syn[c], errors="coerce").median()
            X_syn[c] = pd.to_numeric(X_syn[c], errors="coerce").fillna(med)
            X_test[c] = pd.to_numeric(X_test[c], errors="coerce").fillna(med)
        else:
            mode = X_syn[c].astype(str).mode().iloc[0] if len(X_syn[c].dropna()) else "MISSING"
            X_syn[c] = X_syn[c].astype(str).fillna(mode)
            X_test[c] = X_test[c].astype(str).fillna(mode)

    # one-hot for attacker model
    cols_num = [c for c in feature_cols if pd.api.types.is_numeric_dtype(X_syn[c])]
    cols_cat = [c for c in feature_cols if c not in cols_num]
    ct = ColumnTransformer(
        transformers=[
            ("num", Pipeline([("imp", SimpleImputer(strategy="median")), ("sc", StandardScaler())]), cols_num),
            ("cat", Pipeline([("imp", SimpleImputer(strategy="most_frequent")), ("oh", OneHotEncoder(handle_unknown="ignore", sparse_output=False))]), cols_cat),
        ],
        remainder="drop",
    )
    Xs = ct.fit_transform(X_syn)
    Xt = ct.transform(X_test)

    # baseline
    if pd.api.types.is_numeric_dtype(y_syn):
        baseline_pred = np.full_like(pd.to_numeric(y_test, errors="coerce").to_numpy(), fill_value=float(pd.to_numeric(y_syn, errors="coerce").mean()))
        y_true = pd.to_numeric(y_test, errors="coerce").to_numpy()
        rmse_base = float(np.sqrt(np.mean((baseline_pred - y_true) ** 2)))
    else:
        y_true = y_test.astype(str).to_numpy()
        maj = y_syn.astype(str).value_counts().idxmax()
        baseline_pred = np.array([maj] * len(y_true), dtype=object)
        acc_base = float(accuracy_score(y_true, baseline_pred))

    # attacker model
    if pd.api.types.is_numeric_dtype(y_syn):
        ytr = pd.to_numeric(y_syn, errors="coerce").fillna(pd.to_numeric(y_syn, errors="coerce").median()).to_numpy()
        reg = RandomForestRegressor(n_estimators=300, random_state=seed, n_jobs=-1)
        reg.fit(Xs, ytr)
        pred = reg.predict(Xt)
        rmse = float(np.sqrt(np.mean((pred - y_true) ** 2)))
        # higher risk if attacker reduces error relative to baseline
        risk = max(0.0, (rmse_base - rmse) / (rmse_base + 1e-12))
        return {
            "attribute_task": "regression_rmse",
            "baseline_rmse": rmse_base,
            "attacker_rmse": rmse,
            "attribute_risk": float(risk),
        }
    else:
        ytr = y_syn.astype(str).to_numpy()
        clf = RandomForestClassifier(n_estimators=400, random_state=seed, n_jobs=-1)
        clf.fit(Xs, ytr)
        pred = clf.predict(Xt)
        acc = float(accuracy_score(y_true, pred))
        risk = max(0.0, acc - acc_base)
        return {
            "attribute_task": "classification_accuracy",
            "baseline_accuracy": acc_base,
            "attacker_accuracy": acc,
            "attribute_risk": float(risk),
        }


def linkage_risk_simulation(
    df_real: pd.DataFrame,
    df_syn: pd.DataFrame,
    quasi_id_cols: List[str],
    seed: int,
) -> Dict[str, float]:
    """
    A governance-oriented linkage proxy:
      - Build a quasi-identifier space and compute the nearest synthetic neighbor for each real record.
      - Linkable if within a small radius (adaptive: quantile of NN distances).
      - Unique if exactly one synthetic record lies within that radius.
    """
    rng = np.random.default_rng(seed)

    # prepare quasi-id feature space
    cols = list(quasi_id_cols)
    Xr = df_real[cols].copy()
    Xs = df_syn[cols].copy()

    # simple mixed encoding
    num_cols = [c for c in cols if pd.api.types.is_numeric_dtype(Xr[c])]
    cat_cols = [c for c in cols if c not in num_cols]
    ct = ColumnTransformer(
        transformers=[
            ("num", Pipeline([("imp", SimpleImputer(strategy="median")), ("sc", StandardScaler())]), num_cols),
            ("cat", Pipeline([("imp", SimpleImputer(strategy="most_frequent")), ("oh", OneHotEncoder(handle_unknown="ignore", sparse_output=False))]), cat_cols),
        ],
        remainder="drop",
    )
    Xr_t = ct.fit_transform(Xr)
    Xs_t = ct.transform(Xs)

    nn1 = NearestNeighbors(n_neighbors=1).fit(Xs_t)
    d, _ = nn1.kneighbors(Xr_t, n_neighbors=1)
    d = d.ravel()
    radius = float(np.quantile(d, 0.05))
    # linkable if unusually close
    linkable = d <= radius
    linkable_rate = float(np.mean(linkable))

    # uniqueness within radius
    nnk = NearestNeighbors(radius=radius).fit(Xs_t)
    neigh = nnk.radius_neighbors(Xr_t, return_distance=False)
    uniq = np.array([len(ix) == 1 for ix in neigh], dtype=bool)
    uniqueness_rate = float(np.mean(uniq))

    return {
        "linkage_radius": radius,
        "linkable_rate": linkable_rate,
        "uniqueness_rate": uniqueness_rate,
    }


# =============================================================================
# Representation learning (shared embedding) for topology audits
# =============================================================================

class AutoEncoder(nn.Module):
    def __init__(self, input_dim: int, embed_dim: int, hidden_dim: int):
        super().__init__()
        self.enc1 = nn.Linear(input_dim, hidden_dim)
        self.enc2 = nn.Linear(hidden_dim, hidden_dim)
        self.emb = nn.Linear(hidden_dim, embed_dim)
        self.dec1 = nn.Linear(embed_dim, hidden_dim)
        self.dec2 = nn.Linear(hidden_dim, hidden_dim)
        self.out = nn.Linear(hidden_dim, input_dim)

    def encode(self, x: torch.Tensor) -> torch.Tensor:
        h = F.relu(self.enc1(x))
        h = F.relu(self.enc2(h))
        return self.emb(h)

    def decode(self, z: torch.Tensor) -> torch.Tensor:
        h = F.relu(self.dec1(z))
        h = F.relu(self.dec2(h))
        return self.out(h)

    def forward(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        z = self.encode(x)
        recon = self.decode(z)
        return recon, z



def train_autoencoder(
    X_train: np.ndarray,
    topo_cfg: TopologyConfig,
    seed: int,
    device: torch.device,
) -> AutoEncoder:
    """
    Trains a deterministic autoencoder on the real training representation space.
    The encoder is then reused to embed real test points and synthetic points,
    ensuring a *shared* representation geometry for topology auditing.
    """
    set_global_seed(seed)

    X = X_train.astype(np.float32)
    # Subsample to keep embedding training feasible while preserving geometry signals
    if X.shape[0] > topo_cfg.ae_max_train_rows:
        rng = np.random.default_rng(54321)
        idx = rng.choice(X.shape[0], size=topo_cfg.ae_max_train_rows, replace=False)
        X = X[idx]

    Xtr = torch.from_numpy(X).to(device)
    ds = TensorDataset(Xtr)
    dl = DataLoader(ds, batch_size=topo_cfg.ae_batch_size, shuffle=True, drop_last=False)

    model = AutoEncoder(input_dim=X_train.shape[1], embed_dim=topo_cfg.embedding_dim, hidden_dim=topo_cfg.ae_hidden_dim).to(device)
    opt = torch.optim.Adam(model.parameters(), lr=topo_cfg.ae_lr)

    model.train()
    for _ in range(topo_cfg.ae_epochs):
        for (xb,) in dl:
            opt.zero_grad()
            recon, _z = model(xb)
            loss = F.mse_loss(recon, xb, reduction="mean")
            loss.backward()
            opt.step()

    return model


def encode_with_autoencoder(model: AutoEncoder, X: np.ndarray, device: torch.device) -> np.ndarray:
    model.eval()
    Xt = torch.from_numpy(X.astype(np.float32)).to(device)
    with torch.no_grad():
        Z = model.encode(Xt).detach().cpu().numpy()
    return Z


# =============================================================================
# Persistent homology up to H1 (Vietoris–Rips) with Z2 reduction
# =============================================================================

@dataclass
class Simplex:
    vertices: Tuple[int, ...]
    dim: int
    filt: float


def vr_complex_simplices(D: np.ndarray, max_dim: int = 1) -> List[Simplex]:
    """
    Build Vietoris–Rips simplices up to dimension 2 (needed to kill H1).
    Filtration values follow standard Rips: edge weight; triangle weight = max edge weight.
    """
    n = D.shape[0]
    simplices: List[Simplex] = []
    # vertices
    for i in range(n):
        simplices.append(Simplex((i,), 0, 0.0))
    # edges
    for i in range(n):
        for j in range(i + 1, n):
            simplices.append(Simplex((i, j), 1, float(D[i, j])))
    if max_dim >= 1:
        # triangles (for H1 deaths)
        for i in range(n):
            for j in range(i + 1, n):
                dij = D[i, j]
                for k in range(j + 1, n):
                    filt = float(max(dij, D[i, k], D[j, k]))
                    simplices.append(Simplex((i, j, k), 2, filt))
    # sort by filtration, then dim
    simplices.sort(key=lambda s: (s.filt, s.dim, s.vertices))
    return simplices


def simplex_boundary(simplex: Simplex, simplex_to_index: Dict[Tuple[int, ...], int]) -> int:
    """
    Returns boundary as a bitset int of row indices in simplex ordering.
    Z2 coefficients.
    """
    v = simplex.vertices
    if simplex.dim == 0:
        return 0
    # boundary is all faces of size dim
    bits = 0
    for i in range(len(v)):
        face = v[:i] + v[i + 1 :]
        idx = simplex_to_index.get(face)
        if idx is None:
            raise RuntimeError(f"Missing face {face} in complex.")
        bits ^= (1 << idx)
    return bits


def low_bit_index(bits: int) -> int:
    """
    Index of the lowest set bit (most significant in reduction sense is highest row index),
    but for column reduction we need highest row index => use bit_length-1 on bits.
    """
    return bits.bit_length() - 1


def vr_persistence_diagrams(points: np.ndarray, max_dim: int = 1) -> Dict[int, List[Tuple[float, float]]]:
    """
    Compute persistence diagrams for H0 and H1 using a basic reduction algorithm over Z2.
    This is intended for small subsamples (<= ~140 points) due to O(n^3) triangles.
    """
    # pairwise distances
    D = squareform(pdist(points, metric="euclidean"))
    simplices = vr_complex_simplices(D, max_dim=max_dim)
    simplex_to_index = {s.vertices: i for i, s in enumerate(simplices)}

    # build boundary columns (bitsets)
    boundaries: List[int] = []
    dims = [s.dim for s in simplices]
    filts = [s.filt for s in simplices]

    for s in simplices:
        b = simplex_boundary(s, simplex_to_index)
        boundaries.append(b)

    pivot_to_col: Dict[int, int] = {}
    reduced_cols: Dict[int, int] = {}

    pairs: List[Tuple[int, int]] = []

    for j in range(len(simplices)):
        col = boundaries[j]
        while col != 0:
            i = low_bit_index(col)
            if i in pivot_to_col:
                col ^= reduced_cols[pivot_to_col[i]]
            else:
                break
        if col != 0:
            i = low_bit_index(col)
            pivot_to_col[i] = j
            reduced_cols[j] = col
            pairs.append((i, j))
        else:
            reduced_cols[j] = 0

    # extract diagrams: creator i (dim k) dies at filtration of j
    diagrams: Dict[int, List[Tuple[float, float]]] = {0: [], 1: []}
    paired_creators = set(i for i, _ in pairs)

    for i, j in pairs:
        k = dims[i]
        if k in diagrams and k <= 1:
            birth = filts[i]
            death = filts[j]
            if death >= birth:
                diagrams[k].append((float(birth), float(death)))

    # unpaired creators => infinite death
    for idx in range(len(simplices)):
        k = dims[idx]
        if k <= 1 and idx not in paired_creators:
            # creator if its column reduced to zero and it created a feature of its dimension
            # Standard interpretation: columns with zero reduced boundary correspond to births.
            # Here we approximate: treat all unpaired simplices of dim 0 or 1 as infinite features.
            diagrams[k].append((float(filts[idx]), float("inf")))

    # remove trivial infinite 1D births at 0 that are artifacts (rare in practice)
    diagrams[1] = [(b, d) for (b, d) in diagrams[1] if not (b == 0.0 and math.isinf(d))]
    return diagrams


def diagram_summaries(diag: List[Tuple[float, float]]) -> Dict[str, float]:
    finite = [(b, d) for (b, d) in diag if np.isfinite(d)]
    if len(finite) == 0:
        return {"n_features": 0, "total_persistence": 0.0, "persistent_entropy": 0.0, "mean_lifetime": 0.0}
    lifetimes = np.array([d - b for b, d in finite], dtype=float)
    total = float(lifetimes.sum())
    p = lifetimes / (lifetimes.sum() + 1e-12)
    ent = float(-(p * np.log(p + 1e-12)).sum())
    return {
        "n_features": int(len(finite)),
        "total_persistence": total,
        "persistent_entropy": ent,
        "mean_lifetime": float(lifetimes.mean()),
    }


def betti_curve(diag: List[Tuple[float, float]], eps_grid: np.ndarray) -> np.ndarray:
    """
    Betti_k(eps) = number of features alive at epsilon.
    """
    b = np.zeros_like(eps_grid, dtype=float)
    for birth, death in diag:
        for i, eps in enumerate(eps_grid):
            if eps >= birth and (eps < death or math.isinf(death)):
                b[i] += 1.0
    return b


def point_to_diag_cost(p: Tuple[float, float]) -> float:
    b, d = p
    if not np.isfinite(d):
        return float("inf")
    return abs(d - b) / 2.0


def linf_dist(p: Tuple[float, float], q: Tuple[float, float]) -> float:
    return max(abs(p[0] - q[0]), abs(p[1] - q[1]))


def wasserstein_distance_diagrams(D1: List[Tuple[float, float]], D2: List[Tuple[float, float]], p: int = 1) -> float:
    """
    p-Wasserstein distance with L_infty ground metric, using linear assignment.
    Includes matching to diagonal via replicated diagonal nodes.
    """
    A = [(b, d) for (b, d) in D1 if np.isfinite(d)]
    B = [(b, d) for (b, d) in D2 if np.isfinite(d)]
    n, m = len(A), len(B)
    N = n + m
    if N == 0:
        return 0.0

    # cost matrix N x N
    C = np.zeros((N, N), dtype=float)

    # top-left: A to B
    for i in range(n):
        for j in range(m):
            C[i, j] = linf_dist(A[i], B[j])

    # A to diagonal copies (columns m..N-1)
    for i in range(n):
        c = point_to_diag_cost(A[i])
        C[i, m:] = c

    # diagonal copies of B (rows n..N-1) to B points
    for j in range(m):
        c = point_to_diag_cost(B[j])
        C[n:, j] = c

    # diagonal to diagonal: 0
    C[n:, m:] = 0.0

    row_ind, col_ind = linear_sum_assignment(C)
    costs = C[row_ind, col_ind]
    if p == 1:
        return float(costs.sum())
    return float((np.power(costs, p).sum()) ** (1.0 / p))


def hopcroft_karp(adj: List[List[int]], n_left: int, n_right: int) -> int:
    """
    Maximum bipartite matching via Hopcroft–Karp.
    adj[u] lists neighbors v in right part.
    """
    INF = 10**9
    pair_u = [-1] * n_left
    pair_v = [-1] * n_right
    dist = [0] * n_left

    from collections import deque

    def bfs() -> bool:
        q = deque()
        for u in range(n_left):
            if pair_u[u] == -1:
                dist[u] = 0
                q.append(u)
            else:
                dist[u] = INF
        found = False
        while q:
            u = q.popleft()
            for v in adj[u]:
                pu = pair_v[v]
                if pu != -1 and dist[pu] == INF:
                    dist[pu] = dist[u] + 1
                    q.append(pu)
                if pu == -1:
                    found = True
        return found

    def dfs(u: int) -> bool:
        for v in adj[u]:
            pu = pair_v[v]
            if pu == -1 or (dist[pu] == dist[u] + 1 and dfs(pu)):
                pair_u[u] = v
                pair_v[v] = u
                return True
        dist[u] = INF
        return False

    matching = 0
    while bfs():
        for u in range(n_left):
            if pair_u[u] == -1:
                if dfs(u):
                    matching += 1
    return matching


def bottleneck_distance_diagrams(D1: List[Tuple[float, float]], D2: List[Tuple[float, float]], tol: float = 1e-6) -> float:
    """
    Bottleneck distance via binary search + feasibility (perfect matching) under threshold eps.
    Uses the diagonal-augmentation trick with replicated diagonal nodes.
    """
    A = [(b, d) for (b, d) in D1 if np.isfinite(d)]
    B = [(b, d) for (b, d) in D2 if np.isfinite(d)]
    n, m = len(A), len(B)
    N = n + m
    if N == 0:
        return 0.0

    # precompute all candidate costs
    costs = []
    for i in range(n):
        costs.append(point_to_diag_cost(A[i]))
        for j in range(m):
            costs.append(linf_dist(A[i], B[j]))
    for j in range(m):
        costs.append(point_to_diag_cost(B[j]))
    costs = sorted(set([float(c) for c in costs if np.isfinite(c)]))
    if not costs:
        return 0.0

    def feasible(eps: float) -> bool:
        # build bipartite graph: left size N (A points + m diag copies for B), right size N (B points + n diag copies for A)
        adj = [[] for _ in range(N)]
        # left A points (0..n-1)
        for i in range(n):
            # connect to B points
            for j in range(m):
                if linf_dist(A[i], B[j]) <= eps:
                    adj[i].append(j)
            # connect to any diagonal node on right (m..N-1) if diag cost ok
            if point_to_diag_cost(A[i]) <= eps:
                adj[i].extend(list(range(m, N)))
        # left diag copies for B (n..N-1), each corresponds to some B[j]
        for j in range(m):
            u = n + j
            # can match to B[j] if diag cost ok
            if point_to_diag_cost(B[j]) <= eps:
                adj[u].append(j)
            # can match to any diagonal node (always 0)
            adj[u].extend(list(range(m, N)))

        match = hopcroft_karp(adj, n_left=N, n_right=N)
        return match == N

    # binary search on candidate list
    lo, hi = 0, len(costs) - 1
    best = costs[-1]
    while lo <= hi:
        mid = (lo + hi) // 2
        eps = costs[mid]
        if feasible(eps):
            best = eps
            hi = mid - 1
        else:
            lo = mid + 1
    return float(best)


# =============================================================================
# Output builders for sections 5.1 / 5.2 / 5.3
# =============================================================================

def section_5_1_experimental_design(
    df: pd.DataFrame,
    coltypes: Dict[str, List[str]],
    cfg: RunConfig,
    out_dir: str,
) -> None:
    ensure_dir(out_dir)

    # dataset profile
    profile_rows = []
    for c in df.columns:
        dtype = str(df[c].dtype)
        missing = float(df[c].isna().mean())
        nunique = int(df[c].nunique(dropna=True))
        profile_rows.append({"column": c, "dtype": dtype, "missing_rate": missing, "nunique": nunique})
    profile = pd.DataFrame(profile_rows).sort_values(["missing_rate", "nunique"], ascending=[False, False])
    save_df(profile, os.path.join(out_dir, "dataset_profile.csv"))

    # governance scope
    gov = dataclasses.asdict(cfg.governance)
    gov_tbl = pd.DataFrame(
        [{"field": k, "value": json.dumps(v) if isinstance(v, list) else str(v)} for k, v in gov.items()]
    )
    save_df(gov_tbl, os.path.join(out_dir, "governance_scope.csv"))

    # adversary assumptions / threat model
    thr = dataclasses.asdict(cfg.threat)
    thr_tbl = pd.DataFrame(
        [{"field": k, "value": json.dumps(v) if isinstance(v, list) else str(v)} for k, v in thr.items()]
    )
    save_df(thr_tbl, os.path.join(out_dir, "adversary_assumptions.csv"))

    # column types
    ct_tbl = pd.DataFrame(
        [{"type": k, "columns": ", ".join(v)} for k, v in coltypes.items()]
    )
    save_df(ct_tbl, os.path.join(out_dir, "inferred_column_types.csv"))

    # missingness plot (top 30)
    miss = profile.sort_values("missing_rate", ascending=False).head(30)
    fig = plt.figure(figsize=(10, 5))
    plt.bar(miss["column"], miss["missing_rate"])
    plt.xticks(rotation=75, ha="right")
    plt.ylabel("Missing rate")
    plt.title("Top missingness rates (up to 30 columns)")
    fig_save_close(fig, os.path.join(out_dir, "missingness_top30.png"))

    # generator portfolio + replica strategy
    gens = []
    for g in cfg.generators.generators:
        for r in range(cfg.generators.replicas):
            gens.append({"generator": g, "replica": r, "seed": cfg.generators.base_seed + 1000 * cfg.generators.generators.index(g) + r})
    save_df(pd.DataFrame(gens), os.path.join(out_dir, "generator_portfolio_and_replicas.csv"))


def choose_quasi_ids(df: pd.DataFrame, coltypes: Dict[str, List[str]], cfg: RunConfig) -> List[str]:
    if cfg.evaluation.quasi_id_cols:
        return [c for c in cfg.evaluation.quasi_id_cols if c in df.columns]
    # heuristic: pick 1-2 categorical + 1 numeric
    cands = []
    if coltypes["categorical"]:
        cands.extend(coltypes["categorical"][:2])
    if coltypes["boolean"]:
        cands.extend(coltypes["boolean"][:1])
    if coltypes["numeric"]:
        cands.extend(coltypes["numeric"][:1])
    return cands[:3]


def section_5_2_utility_privacy(
    df_train: pd.DataFrame,
    df_test: pd.DataFrame,
    pre: MixedTabularPreprocessor,
    X_train: np.ndarray,
    X_test: np.ndarray,
    y_train: Optional[np.ndarray],
    y_test: Optional[np.ndarray],
    coltypes: Dict[str, List[str]],
    cfg: RunConfig,
    syn_by_gen: Dict[str, List[pd.DataFrame]],
    out_dir: str,
) -> Dict[str, Any]:
    ensure_dir(out_dir)

    # statistical fidelity + MMD
    fidelity_rows = []
    mmd_rows = []
    for gen, reps in syn_by_gen.items():
        for r, df_syn in enumerate(reps):
            fid = compute_fidelity_metrics(df_test, df_syn, coltypes["numeric"], coltypes["categorical"], coltypes["boolean"])
            X_syn = pre.transform(df_syn)
            mmd2 = rbf_mmd2(X_test, X_syn, gamma=None, max_points=500, seed=cfg.generators.base_seed + r)
            row = {"generator": gen, "replica": r, **fid, "mmd2_rbf": mmd2}
            fidelity_rows.append(row)

    fidelity_df = pd.DataFrame(fidelity_rows)
    save_df(fidelity_df, os.path.join(out_dir, "fidelity_metrics_by_generator_replica.csv"))

    # downstream task transfer (if target provided)
    downstream_df = pd.DataFrame()
    fairness_df = pd.DataFrame()
    baseline_metrics = {}
    if cfg.evaluation.target_col is not None and y_train is not None and y_test is not None:
        task_type = cfg.evaluation.task_type
        if task_type == "auto":
            task_type = infer_task_type(pd.Series(y_train))
        # baseline: train on real train
        baseline_metrics = train_eval_downstream(X_train, y_train, X_test, y_test, task_type, seed=cfg.evaluation.random_state)
        base_row = {"generator": "REAL_TRAIN", "replica": -1, **baseline_metrics}
        down_rows = [base_row]

        for gen, reps in syn_by_gen.items():
            for r, df_syn in enumerate(reps):
                X_syn = pre.transform(df_syn)
                # align y for synthetic by bootstrapping target distribution from real train
                # NOTE: synthesis script assumes target is included in df_syn if present in df_train;
                # if target exists, generators included it. If not, derive by sampling y_train.
                if cfg.evaluation.target_col in df_syn.columns:
                    y_syn = df_syn[cfg.evaluation.target_col].to_numpy()
                else:
                    rng = np.random.default_rng(cfg.generators.base_seed + r)
                    y_syn = rng.choice(y_train, size=len(X_syn), replace=True)
                met = train_eval_downstream(X_syn, y_syn, X_test, y_test, task_type, seed=cfg.evaluation.random_state + 7 * r)
                down_rows.append({"generator": gen, "replica": r, **met})

        downstream_df = pd.DataFrame(down_rows)
        save_df(downstream_df, os.path.join(out_dir, "downstream_task_transfer.csv"))

        # fairness diagnostics (binary only)
        if cfg.evaluation.group_col is not None and cfg.evaluation.group_col in df_test.columns and task_type == "classification":
            # compute with a single chosen model (RandomForest) for baseline and best synthetic later
            # baseline rf
            rf = RandomForestClassifier(n_estimators=250, random_state=cfg.evaluation.random_state, n_jobs=-1)
            rf.fit(X_train, y_train)
            y_pred_base = rf.predict(X_test)

            group = df_test[cfg.evaluation.group_col].astype(str).to_numpy()

            # only if binary labels 0/1
            uniq = np.unique(y_test)
            if len(uniq) == 2 and set(uniq) <= {0, 1}:
                fairness_base = fairness_diagnostics_binary(y_test, y_pred_base, group)
                fairness_base["model"] = "RF_REAL_TRAIN"

                # pick best synthetic by roc_auc if available
                best = downstream_df[downstream_df["generator"] != "REAL_TRAIN"].copy()
                if "rf_roc_auc" in best.columns and best["rf_roc_auc"].notna().any():
                    best_row = best.sort_values("rf_roc_auc", ascending=False).iloc[0]
                else:
                    best_row = best.sort_values("rf_macro_f1", ascending=False).iloc[0]
                best_gen = str(best_row["generator"])
                best_rep = int(best_row["replica"])
                df_best = syn_by_gen[best_gen][best_rep]
                X_best = pre.transform(df_best)
                y_best = df_best[cfg.evaluation.target_col].to_numpy() if cfg.evaluation.target_col in df_best.columns else y_train
                rf2 = RandomForestClassifier(n_estimators=250, random_state=cfg.evaluation.random_state + 99, n_jobs=-1)
                rf2.fit(X_best, y_best)
                y_pred_syn = rf2.predict(X_test)
                fairness_syn = fairness_diagnostics_binary(y_test, y_pred_syn, group)
                fairness_syn["model"] = f"RF_SYN_TRAIN({best_gen},rep={best_rep})"

                fairness_df = pd.concat([fairness_base, fairness_syn], ignore_index=True)
                save_df(fairness_df, os.path.join(out_dir, "fairness_diagnostics_binary.csv"))

                # fairness plot: TPR gap
                fig = plt.figure(figsize=(8, 4))
                for model in fairness_df["model"].unique():
                    d = fairness_df[fairness_df["model"] == model].sort_values("group")
                    plt.plot(d["group"], d["TPR"], marker="o", label=model)
                plt.xticks(rotation=45, ha="right")
                plt.ylabel("TPR")
                plt.title("Fairness diagnostic: per-group TPR (binary)")
                plt.legend()
                fig_save_close(fig, os.path.join(out_dir, "fairness_tpr_by_group.png"))

    # privacy risk metrics
    risk_rows = []
    membership_curves = None
    for gen, reps in syn_by_gen.items():
        for r, df_syn in enumerate(reps):
            X_syn = pre.transform(df_syn)

            # membership: members = real train, non-members = real test
            mem = membership_inference_attack(X_members=X_train, X_nonmembers=X_test, X_syn=X_syn, seed=cfg.generators.base_seed + r)
            quasi_ids = choose_quasi_ids(pd.concat([df_train, df_test], axis=0), coltypes, cfg)
            link = linkage_risk_simulation(df_real=df_test, df_syn=df_syn, quasi_id_cols=quasi_ids, seed=cfg.generators.base_seed + 10 + r)

            attr = {"attribute_risk": np.nan}
            if cfg.evaluation.sensitive_col is not None and cfg.evaluation.sensitive_col in df_train.columns:
                sens = cfg.evaluation.sensitive_col
                feat_cols = [c for c in df_train.columns if c != sens and c != cfg.evaluation.target_col and c != cfg.evaluation.time_col and (c in df_syn.columns) and (c in df_test.columns)]
                attr = attribute_inference_risk(df_syn=df_syn, df_real_test=df_test, sensitive_col=sens, feature_cols=feat_cols, seed=cfg.generators.base_seed + 20 + r)

            risk_rows.append(
                {
                    "generator": gen,
                    "replica": r,
                    "membership_auc": mem["membership_auc"],
                    "membership_advantage": mem["membership_advantage"],
                    "linkage_radius": link["linkage_radius"],
                    "linkable_rate": link["linkable_rate"],
                    "uniqueness_rate": link["uniqueness_rate"],
                    "attribute_risk": attr.get("attribute_risk", np.nan),
                }
            )

            if membership_curves is None:
                membership_curves = (mem["roc_fpr"], mem["roc_tpr"])

    risk_df = pd.DataFrame(risk_rows)
    save_df(risk_df, os.path.join(out_dir, "privacy_risk_metrics.csv"))

    # membership ROC curve plot: show first curve as representative (all curves are also in the CSV via AUC/advantage)
    if membership_curves is not None:
        fpr, tpr = membership_curves
        fig = plt.figure(figsize=(5, 5))
        plt.plot(fpr, tpr)
        plt.plot([0, 1], [0, 1], linestyle="--")
        plt.xlabel("False Positive Rate")
        plt.ylabel("True Positive Rate")
        plt.title("Membership inference proxy ROC (representative)")
        fig_save_close(fig, os.path.join(out_dir, "membership_attack_roc.png"))

    # trade-off plot (utility vs privacy)
    # Utility composite: inverse of (mmd + wasserstein + js + corr gap)
    comp_rows = []
    merged = fidelity_df.merge(risk_df, on=["generator", "replica"], how="inner")
    for _, row in merged.iterrows():
        util_parts = [
            1.0 / (1.0 + float(row["mmd2_rbf"])),
            1.0 / (1.0 + float(row["numeric_wasserstein_mean"])),
            1.0 / (1.0 + float(row["categorical_js_mean"])),
            1.0 / (1.0 + float(row["spearman_corr_gap_mean"])),
        ]
        util = float(np.nanmean(util_parts))
        priv = float(np.nanmean([row["membership_advantage"], row["uniqueness_rate"], row.get("attribute_risk", np.nan)]))
        comp_rows.append(
            {
                "generator": row["generator"],
                "replica": int(row["replica"]),
                "utility_score": util,
                "privacy_risk_score": priv,
            }
        )
    comp_df = pd.DataFrame(comp_rows)
    save_df(comp_df, os.path.join(out_dir, "utility_privacy_composite.csv"))

    fig = plt.figure(figsize=(7, 5))
    for gen in comp_df["generator"].unique():
        d = comp_df[comp_df["generator"] == gen]
        plt.scatter(d["privacy_risk_score"], d["utility_score"], label=gen, alpha=0.85)
    plt.xlabel("Privacy risk score (lower is better)")
    plt.ylabel("Utility score (higher is better)")
    plt.title("Utility–Privacy trade-off (replicas as points)")
    plt.legend()
    fig_save_close(fig, os.path.join(out_dir, "utility_privacy_tradeoff_scatter.png"))

    return {
        "fidelity_df": fidelity_df,
        "risk_df": risk_df,
        "downstream_df": downstream_df,
        "baseline_metrics": baseline_metrics,
        "composite_df": comp_df,
    }


def pareto_frontier(df: pd.DataFrame, x: str, y: str, minimize_x: bool = True, maximize_y: bool = True) -> pd.DataFrame:
    """
    Computes non-dominated set for 2D objectives:
      - x: minimize if minimize_x else maximize
      - y: maximize if maximize_y else minimize
    """
    pts = df.copy().reset_index(drop=True)
    keep = []
    for i in range(len(pts)):
        dominated = False
        xi, yi = float(pts.loc[i, x]), float(pts.loc[i, y])
        for j in range(len(pts)):
            if i == j:
                continue
            xj, yj = float(pts.loc[j, x]), float(pts.loc[j, y])
            better_x = (xj <= xi) if minimize_x else (xj >= xi)
            better_y = (yj >= yi) if maximize_y else (yj <= yi)
            strictly = ((xj < xi) if minimize_x else (xj > xi)) or ((yj > yi) if maximize_y else (yj < yi))
            if better_x and better_y and strictly:
                dominated = True
                break
        if not dominated:
            keep.append(i)
    return pts.loc[keep].copy()


def section_5_3_topological(
    df_train: pd.DataFrame,
    df_test: pd.DataFrame,
    pre: MixedTabularPreprocessor,
    X_train: np.ndarray,
    X_test: np.ndarray,
    coltypes: Dict[str, List[str]],
    cfg: RunConfig,
    syn_by_gen: Dict[str, List[pd.DataFrame]],
    analysis_5_2: Dict[str, Any],
    out_dir: str,
) -> None:
    ensure_dir(out_dir)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Select "best" synthetic configuration based on composite (highest utility / lowest privacy)
    comp_df: pd.DataFrame = analysis_5_2["composite_df"]
    comp_df = comp_df.copy()
    comp_df["score"] = comp_df["utility_score"] - comp_df["privacy_risk_score"]
    best_row = comp_df.sort_values("score", ascending=False).iloc[0]
    best_gen = str(best_row["generator"])
    best_rep = int(best_row["replica"])
    df_best = syn_by_gen[best_gen][best_rep]
    X_best = pre.transform(df_best)

    # Learn a shared embedding using an autoencoder trained on real train
    ae_model = train_autoencoder(X_train, cfg.topology, seed=cfg.evaluation.random_state, device=device)

    # Shared embeddings for the real test set and the chosen synthetic sample
    Z_test = encode_with_autoencoder(ae_model, X_test, device=device)
    Z_syn = encode_with_autoencoder(ae_model, X_best, device=device)

    # Subsample for Rips persistence
    def subsample(Z: np.ndarray, n: int, seed: int) -> np.ndarray:
        rng = np.random.default_rng(seed)
        if Z.shape[0] <= n:
            return Z
        idx = rng.choice(Z.shape[0], size=n, replace=False)
        return Z[idx]

    n_sub = min(cfg.topology.subsample_n, cfg.topology.max_points_for_rips)
    Zr = subsample(Z_test, n_sub, seed=cfg.generators.base_seed + 1)
    Zs = subsample(Z_syn, n_sub, seed=cfg.generators.base_seed + 2)

    # persistence diagrams
    diag_real = vr_persistence_diagrams(Zr, max_dim=cfg.topology.rips_max_dim)
    diag_syn = vr_persistence_diagrams(Zs, max_dim=cfg.topology.rips_max_dim)

    # summaries
    rows = []
    for dim in [0, 1]:
        sR = diagram_summaries(diag_real[dim])
        sS = diagram_summaries(diag_syn[dim])
        rows.append({"slice": "global_real", "dim": dim, **sR})
        rows.append({"slice": f"global_syn({best_gen},rep={best_rep})", "dim": dim, **sS})
    save_df(pd.DataFrame(rows), os.path.join(out_dir, "persistence_summaries_global.csv"))

    # distances
    dist_rows = []
    for dim in [0, 1]:
        bdist = bottleneck_distance_diagrams(diag_real[dim], diag_syn[dim])
        w1 = wasserstein_distance_diagrams(diag_real[dim], diag_syn[dim], p=1)
        w2 = wasserstein_distance_diagrams(diag_real[dim], diag_syn[dim], p=2)
        dist_rows.append(
            {
                "comparison": f"real_test vs syn_best({best_gen},rep={best_rep})",
                "dim": dim,
                "bottleneck": float(bdist),
                "wasserstein_1": float(w1),
                "wasserstein_2": float(w2),
            }
        )
    dist_df = pd.DataFrame(dist_rows)
    save_df(dist_df, os.path.join(out_dir, "diagram_distances_global.csv"))

    # Betti curves plot
    # Choose epsilon grid from combined finite deaths
    def finite_deaths(di: List[Tuple[float, float]]) -> List[float]:
        return [d for _, d in di if np.isfinite(d)]

    deaths = finite_deaths(diag_real[0]) + finite_deaths(diag_syn[0]) + finite_deaths(diag_real[1]) + finite_deaths(diag_syn[1])
    if deaths:
        eps_max = float(np.quantile(deaths, 0.95))
    else:
        eps_max = 1.0
    eps = np.linspace(0.0, eps_max, cfg.topology.betti_grid_size)

    fig = plt.figure(figsize=(10, 4))
    for dim in [0, 1]:
        br = betti_curve(diag_real[dim], eps)
        bs = betti_curve(diag_syn[dim], eps)
        plt.plot(eps, br, label=f"Betti_{dim} (real)")
        plt.plot(eps, bs, linestyle="--", label=f"Betti_{dim} (synthetic)")
    plt.xlabel("Scale ε")
    plt.ylabel("Betti number")
    plt.title(f"Betti curves in embedding space (best synthetic: {best_gen}, replica {best_rep})")
    plt.legend()
    fig_save_close(fig, os.path.join(out_dir, "betti_curves_global.png"))

    # subgroup integrity (optional)
    if cfg.evaluation.group_col is not None and cfg.evaluation.group_col in df_test.columns:
        group = df_test[cfg.evaluation.group_col].astype(str).to_numpy()
        sub_rows = []
        for g in sorted(pd.Series(group).unique()):
            mask = (pd.Series(group) == g).to_numpy()
            if mask.sum() < 20:
                continue
            Zrg = subsample(Z_test[mask], min(n_sub, int(mask.sum())), seed=cfg.generators.base_seed + 3)
            # synthetic subgroup approximated by conditioning via nearest labels in real subgroup:
            # since synthetic may not preserve group column perfectly, use synthetic rows whose group matches g when available
            if cfg.evaluation.group_col in df_best.columns:
                mask_s = (df_best[cfg.evaluation.group_col].astype(str) == g).to_numpy()
                if mask_s.sum() >= 20:
                    Zsg = subsample(Z_syn[mask_s[:len(Z_syn)]], min(n_sub, int(mask_s.sum())), seed=cfg.generators.base_seed + 4)
                else:
                    Zsg = subsample(Z_syn, n_sub, seed=cfg.generators.base_seed + 5)
            else:
                Zsg = subsample(Z_syn, n_sub, seed=cfg.generators.base_seed + 5)

            dR = vr_persistence_diagrams(Zrg, max_dim=cfg.topology.rips_max_dim)
            dS = vr_persistence_diagrams(Zsg, max_dim=cfg.topology.rips_max_dim)
            for dim in [0, 1]:
                bdist = bottleneck_distance_diagrams(dR[dim], dS[dim])
                w1 = wasserstein_distance_diagrams(dR[dim], dS[dim], p=1)
                sub_rows.append(
                    {
                        "group": g,
                        "dim": dim,
                        "bottleneck": float(bdist),
                        "wasserstein_1": float(w1),
                        "n_real": int(mask.sum()),
                        "n_syn": int(len(Zsg)),
                    }
                )
        sub_df = pd.DataFrame(sub_rows)
        save_df(sub_df, os.path.join(out_dir, "subgroup_topology_distances.csv"))

        if not sub_df.empty:
            fig = plt.figure(figsize=(8, 4))
            d0 = sub_df[sub_df["dim"] == 0].sort_values("bottleneck", ascending=False)
            plt.bar(d0["group"], d0["bottleneck"])
            plt.xticks(rotation=45, ha="right")
            plt.ylabel("Bottleneck distance (H0)")
            plt.title("Subgroup integrity: topology distance by group (H0)")
            fig_save_close(fig, os.path.join(out_dir, "subgroup_bottleneck_H0.png"))

    # temporal windows (optional)
    if cfg.evaluation.time_col is not None and cfg.evaluation.time_col in df_test.columns:
        tcol = cfg.evaluation.time_col
        df_t = df_test.copy()
        df_t[tcol] = pd.to_datetime(df_t[tcol], errors="coerce")
        df_t = df_t.dropna(subset=[tcol]).sort_values(tcol)
        if len(df_t) >= 100:
            # sliding windows by quantiles (approximate equal-sized)
            q_edges = np.linspace(0.0, 1.0, 6)  # 5 windows
            edges = df_t[tcol].quantile(q_edges).to_list()
            win_rows = []
            for i in range(len(edges) - 1):
                a, b = edges[i], edges[i + 1]
                w = df_t[(df_t[tcol] >= a) & (df_t[tcol] <= b)]
                if len(w) < 20:
                    continue
                Xw = pre.transform(w.drop(columns=[cfg.evaluation.target_col], errors="ignore"))
                # Embed the window in the shared representation space
                Zw = encode_with_autoencoder(ae_model, Xw, device=device)
                Zw = subsample(Zw, min(n_sub, len(Zw)), seed=cfg.generators.base_seed + 60 + i)
                # synthetic window: approximate by sampling from synthetic and using its time distribution if present
                if tcol in df_best.columns:
                    df_syn_t = df_best.copy()
                    df_syn_t[tcol] = pd.to_datetime(df_syn_t[tcol], errors="coerce")
                    df_syn_t = df_syn_t.dropna(subset=[tcol])
                    ws = df_syn_t[(df_syn_t[tcol] >= a) & (df_syn_t[tcol] <= b)]
                    if len(ws) >= 20:
                        Xws = pre.transform(ws.drop(columns=[cfg.evaluation.target_col], errors="ignore"))
                        Zws = encode_with_autoencoder(ae_model, Xws, device=device)
                    else:
                        Zws = Z_syn
                else:
                    Zws = Z_syn
                Zws = subsample(Zws, min(n_sub, len(Zws)), seed=cfg.generators.base_seed + 80 + i)

                dR = vr_persistence_diagrams(Zw, max_dim=cfg.topology.rips_max_dim)
                dS = vr_persistence_diagrams(Zws, max_dim=cfg.topology.rips_max_dim)
                # focus on H0 bottleneck for window
                bdist = bottleneck_distance_diagrams(dR[0], dS[0])
                win_rows.append(
                    {
                        "window": i,
                        "start": str(a),
                        "end": str(b),
                        "n_real": int(len(w)),
                        "n_syn": int(len(Zws)),
                        "bottleneck_H0": float(bdist),
                    }
                )
            win_df = pd.DataFrame(win_rows)
            save_df(win_df, os.path.join(out_dir, "temporal_window_topology.csv"))
            if not win_df.empty:
                fig = plt.figure(figsize=(9, 4))
                plt.plot(win_df["window"], win_df["bottleneck_H0"], marker="o")
                plt.xlabel("Window index (chronological)")
                plt.ylabel("Bottleneck distance (H0)")
                plt.title("Temporal-window topology discrepancy (H0)")
                fig_save_close(fig, os.path.join(out_dir, "temporal_window_bottleneck_H0.png"))

    # concise note on the chosen best config
    save_text(
        f"Best synthetic configuration selected for topology auditing: generator={best_gen}, replica={best_rep}\n"
        f"Selection criterion: (utility_score - privacy_risk_score) over replicas.\n",
        os.path.join(out_dir, "selected_best_synthetic.txt"),
    )


# =============================================================================
# Orchestration
# =============================================================================

def generate_demo_dataset(n: int = 4000, seed: int = 42) -> pd.DataFrame:
    """
    Creates a mixed-type, governance-styled demo dataset (tabular + time index + group + target).
    This is only used when --data_path is omitted.
    """
    rng = np.random.default_rng(seed)
    # numeric
    income = rng.lognormal(mean=10.2, sigma=0.6, size=n)
    age = rng.integers(18, 85, size=n)
    visits = rng.poisson(lam=3.0, size=n)
    # categorical
    region = rng.choice(["North", "Center", "South"], size=n, p=[0.28, 0.44, 0.28])
    program = rng.choice(["A", "B", "C", "D"], size=n, p=[0.25, 0.30, 0.25, 0.20])
    # group (protected-like)
    group = rng.choice(["G1", "G2", "G3"], size=n, p=[0.55, 0.30, 0.15])
    # time
    start = np.datetime64("2023-01-01")
    days = rng.integers(0, 730, size=n)
    date = start + days.astype("timedelta64[D]")
    # target: binary risk-like outcome
    logit = -3.0 + 0.000015 * income + 0.02 * (age - 40) + 0.12 * visits + (program == "D") * 0.6 + (group == "G3") * 0.25
    p = 1 / (1 + np.exp(-logit))
    y = rng.binomial(1, np.clip(p, 0.01, 0.99), size=n)

    df = pd.DataFrame(
        {
            "income": income,
            "age": age,
            "visits": visits,
            "region": region,
            "program": program,
            "group": group,
            "date": pd.to_datetime(date.astype("datetime64[ns]")),
            "target": y.astype(int),
            "sensitive_attr": rng.choice(["S0", "S1"], size=n, p=[0.7, 0.3]),
        }
    )
    # inject missingness
    miss_idx = rng.choice(n, size=int(0.03 * n), replace=False)
    df.loc[miss_idx, "income"] = np.nan
    miss_idx = rng.choice(n, size=int(0.02 * n), replace=False)
    df.loc[miss_idx, "program"] = np.nan
    return df


def load_dataset(path: Optional[str]) -> pd.DataFrame:
    if path is None:
        return generate_demo_dataset()
    path = str(path)
    if not os.path.exists(path):
        raise FileNotFoundError(f"Data path not found: {path}")
    ext = os.path.splitext(path)[1].lower()
    if ext in [".csv"]:
        return pd.read_csv(path)
    if ext in [".xlsx", ".xls"]:
        return pd.read_excel(path)
    if ext in [".parquet"]:
        return pd.read_parquet(path)
    raise ValueError(f"Unsupported file extension: {ext}")


def run_pipeline(cfg: RunConfig, data_path: Optional[str], output_dir: Optional[str]) -> str:
    # output layout
    root = output_dir or cfg.output_root
    run_root = os.path.join(root, cfg.run_id)
    if os.path.exists(run_root):
        shutil.rmtree(run_root)
    ensure_dir(run_root)

    out_51 = os.path.join(run_root, "5_1_experimental_design")
    out_52 = os.path.join(run_root, "5_2_utility_privacy_tradeoffs")
    out_53 = os.path.join(run_root, "5_3_topological_auditing")
    ensure_dir(out_51); ensure_dir(out_52); ensure_dir(out_53)

    # load data
    df = load_dataset(data_path)

    # configure evaluation columns
    if cfg.evaluation.time_col is None and "date" in df.columns:
        cfg.evaluation.time_col = "date"
    if cfg.evaluation.target_col is None and "target" in df.columns:
        cfg.evaluation.target_col = "target"
    if cfg.evaluation.group_col is None and "group" in df.columns:
        cfg.evaluation.group_col = "group"
    if cfg.evaluation.sensitive_col is None and "sensitive_attr" in df.columns:
        cfg.evaluation.sensitive_col = "sensitive_attr"

    # ensure time parsing
    if cfg.evaluation.time_col is not None and cfg.evaluation.time_col in df.columns:
        df[cfg.evaluation.time_col] = pd.to_datetime(df[cfg.evaluation.time_col], errors="coerce")

    # infer types
    coltypes = infer_column_types(df, time_col=cfg.evaluation.time_col, target_col=cfg.evaluation.target_col)

    # 5.1 artifacts
    section_5_1_experimental_design(df, coltypes, cfg, out_51)

    # train/test split (temporal or random)
    target_col = cfg.evaluation.target_col
    time_col = cfg.evaluation.time_col
    df_model = df.copy()

    # drop rows without target for downstream tasks
    if target_col is not None and target_col in df_model.columns:
        df_model = df_model.dropna(subset=[target_col])

    if time_col is not None and cfg.evaluation.temporal_split and time_col in df_model.columns:
        # chronological split to prevent leakage
        df_model = df_model.dropna(subset=[time_col]).sort_values(time_col)
        n = len(df_model)
        cut = int((1.0 - cfg.evaluation.test_size) * n)
        df_train = df_model.iloc[:cut].copy()
        df_test = df_model.iloc[cut:].copy()
    else:
        # random split; stratify if classification/binary
        strat = None
        if target_col is not None and target_col in df_model.columns:
            ytemp = df_model[target_col]
            if infer_task_type(ytemp) == "classification":
                strat = ytemp
        df_train, df_test = train_test_split(
            df_model, test_size=cfg.evaluation.test_size, random_state=cfg.evaluation.random_state, stratify=strat
        )

    # define feature columns for preprocessing
    # exclude time and target for the model matrix; keep group/sensitive as features if present (auditing may require)
    drop_cols = []
    if time_col is not None and time_col in df_train.columns:
        drop_cols.append(time_col)
    if target_col is not None and target_col in df_train.columns:
        drop_cols.append(target_col)

    df_train_X = df_train.drop(columns=drop_cols, errors="ignore")
    df_test_X = df_test.drop(columns=drop_cols, errors="ignore")

    # Preprocessor
    pre = MixedTabularPreprocessor(coltypes["numeric"], coltypes["categorical"], coltypes["boolean"])
    pre.fit(df_train_X)
    X_train = pre.transform(df_train_X)
    X_test = pre.transform(df_test_X)

    # labels for downstream
    y_train = None
    y_test = None
    if target_col is not None and target_col in df_train.columns:
        y_train = df_train[target_col].to_numpy()
        y_test = df_test[target_col].to_numpy()
        # enforce numeric labels for classification if possible
        if infer_task_type(pd.Series(y_train)) == "classification":
            # map to 0..K-1 if needed
            uniq = sorted(pd.unique(pd.Series(y_train)))
            mapping = {v: i for i, v in enumerate(uniq)}
            y_train = np.array([mapping[v] for v in y_train])
            y_test = np.array([mapping[v] for v in y_test])

    # generator portfolio training
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    syn_by_gen: Dict[str, List[pd.DataFrame]] = {}

    # Ensure target/time are carried into synthesis for evaluation convenience:
    # here, generators are trained on full df_train (including target/time) but sampled outputs drop time by default
    # for topology/time windows, time is retained if present.
    df_train_for_gen = df_train.copy()

    # For preprocessing inside generators, build a preprocessor on X-only columns and inverse back to X-only.
    # Then re-attach target/time by bootstrapping from real train.
    for gen_name in cfg.generators.generators:
        syn_by_gen[gen_name] = []
        for r in range(cfg.generators.replicas):
            seed = cfg.generators.base_seed + 1000 * cfg.generators.generators.index(gen_name) + r
            set_global_seed(seed)

            if gen_name == "bootstrap":
                gen = BootstrapNoiseGenerator(numeric_cols=coltypes["numeric"], noise_scale=cfg.generators.bootstrap_noise_scale)
                gen.fit(df_train_for_gen, pre, cfg)
                syn = gen.sample(len(df_test), seed=seed)
            elif gen_name == "copula":
                gen = GaussianCopulaGenerator(coltypes["numeric"], coltypes["categorical"], coltypes["boolean"])
                gen.fit(df_train_for_gen, pre, cfg)
                syn = gen.sample(len(df_test), seed=seed)
            elif gen_name == "vae":
                # Train VAE on X-only
                vae_gen = VAEGenerator(pre=pre, cfg=cfg.generators, device=device)
                vae_gen.fit(df_train_X, pre, cfg)
                syn_X = vae_gen.sample(len(df_test), seed=seed)
                # attach target/time/group/sensitive by sampling from train (keeps marginal distributions)
                syn = syn_X.copy()
                for extra in [target_col, time_col]:
                    if extra is not None and extra in df_train.columns:
                        rng = np.random.default_rng(seed + 123)
                        syn[extra] = rng.choice(df_train[extra].to_numpy(), size=len(syn), replace=True)
                # also attach group and sensitive if they were dropped
                for extra in [cfg.evaluation.group_col, cfg.evaluation.sensitive_col]:
                    if extra is not None and extra in df_train.columns and extra not in syn.columns:
                        rng = np.random.default_rng(seed + 321)
                        syn[extra] = rng.choice(df_train[extra].astype(str).to_numpy(), size=len(syn), replace=True)
            else:
                raise ValueError(f"Unknown generator: {gen_name}")

            # Ensure required columns exist (target/time/group/sensitive) for downstream audits.
            for extra in [target_col, time_col, cfg.evaluation.group_col, cfg.evaluation.sensitive_col]:
                if extra is not None and extra in df_train.columns and extra not in syn.columns:
                    rng = np.random.default_rng(seed + 777)
                    syn[extra] = rng.choice(df_train[extra].to_numpy(), size=len(syn), replace=True)

            syn_by_gen[gen_name].append(syn)

            # save the synthetic replica dataset itself (auditable artifact)
            save_df(syn, os.path.join(out_52, f"synthetic_{gen_name}_rep{r}.csv"))

    # 5.2 artifacts (utility/privacy trade-offs)
    analysis_5_2 = section_5_2_utility_privacy(
        df_train=df_train,
        df_test=df_test,
        pre=pre,
        X_train=X_train,
        X_test=X_test,
        y_train=y_train,
        y_test=y_test,
        coltypes=coltypes,
        cfg=cfg,
        syn_by_gen=syn_by_gen,
        out_dir=out_52,
    )

    # Add Pareto frontier table based on composite scores
    comp = analysis_5_2["composite_df"].copy()
    frontier = pareto_frontier(comp, x="privacy_risk_score", y="utility_score", minimize_x=True, maximize_y=True)
    save_df(frontier, os.path.join(out_52, "pareto_frontier_utility_privacy.csv"))

    # 5.3 artifacts (topological auditing outcomes)
    section_5_3_topological(
        df_train=df_train,
        df_test=df_test,
        pre=pre,
        X_train=X_train,
        X_test=X_test,
        coltypes=coltypes,
        cfg=cfg,
        syn_by_gen=syn_by_gen,
        analysis_5_2=analysis_5_2,
        out_dir=out_53,
    )

    # Run metadata card
    card = {
        "run_id": cfg.run_id,
        "created_at": _dt.datetime.now().isoformat(),
        "data_path": data_path or "DEMO_DATASET_GENERATED_IN_SCRIPT",
        "output_root": run_root,
        "governance_scope": dataclasses.asdict(cfg.governance),
        "threat_model": dataclasses.asdict(cfg.threat),
        "evaluation": dataclasses.asdict(cfg.evaluation),
        "generator_config": dataclasses.asdict(cfg.generators),
        "topology_config": dataclasses.asdict(cfg.topology),
        "acceptance_config": dataclasses.asdict(cfg.acceptance),
    }
    save_json(card, os.path.join(run_root, "run_card.json"))

    # Minimal README describing where to find Section 5 artifacts
    readme = (
        "RESULTS FOLDER STRUCTURE (mapped to Section 5)\n"
        "---------------------------------------------\n"
        "5_1_experimental_design/\n"
        "  - dataset_profile.csv\n"
        "  - governance_scope.csv\n"
        "  - adversary_assumptions.csv\n"
        "  - inferred_column_types.csv\n"
        "  - generator_portfolio_and_replicas.csv\n"
        "  - missingness_top30.png\n"
        "\n"
        "5_2_utility_privacy_tradeoffs/\n"
        "  - synthetic_<generator>_rep<k>.csv\n"
        "  - fidelity_metrics_by_generator_replica.csv\n"
        "  - downstream_task_transfer.csv (if target provided)\n"
        "  - fairness_diagnostics_binary.csv + fairness_tpr_by_group.png (if binary + group)\n"
        "  - privacy_risk_metrics.csv\n"
        "  - membership_attack_roc.png\n"
        "  - utility_privacy_composite.csv\n"
        "  - utility_privacy_tradeoff_scatter.png\n"
        "  - pareto_frontier_utility_privacy.csv\n"
        "\n"
        "5_3_topological_auditing/\n"
        "  - selected_best_synthetic.txt\n"
        "  - persistence_summaries_global.csv\n"
        "  - diagram_distances_global.csv\n"
        "  - betti_curves_global.png\n"
        "  - subgroup_topology_distances.csv + subgroup_bottleneck_H0.png (if group)\n"
        "  - temporal_window_topology.csv + temporal_window_bottleneck_H0.png (if time)\n"
        "\n"
        "Reproducibility: See run_card.json for seeds and configuration.\n"
    )
    save_text(readme, os.path.join(run_root, "README.txt"))

    return run_root


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Synthetic Data Auditing Pipeline (Utility, Privacy, Topology).")
    p.add_argument("--data_path", type=str, default=None, help="Path to CSV/XLSX/Parquet dataset. If omitted, uses a demo dataset.")
    p.add_argument("--output_dir", type=str, default="results", help="Output root directory.")
    p.add_argument("--target", type=str, default=None, help="Target column for downstream task transfer.")
    p.add_argument("--group_col", type=str, default=None, help="Group column for subgroup/fairness audits.")
    p.add_argument("--time_col", type=str, default=None, help="Time column for temporal splits/windows (optional).")
    p.add_argument("--temporal_split", action="store_true", help="Use chronological split if time_col is provided.")
    p.add_argument("--sensitive_col", type=str, default=None, help="Sensitive attribute for attribute inference risk (optional).")
    p.add_argument("--quasi_ids", type=str, default=None, help="Comma-separated quasi-identifier columns for linkage risk (optional).")
    p.add_argument("--replicas", type=int, default=3, help="Number of synthetic replicas per generator.")
    p.add_argument("--seed", type=int, default=2026, help="Base random seed.")
    p.add_argument("--vae_epochs", type=int, default=None, help="Epochs for the Tabular VAE generator (optional).")
    p.add_argument("--ae_epochs", type=int, default=None, help="Epochs for the embedding autoencoder (optional).")
    p.add_argument("--subsample_n", type=int, default=None, help="Point-cloud subsample size for persistent homology (optional).")
    p.add_argument("--rips_max_dim", type=int, default=None, choices=[0, 1], help="Max homology dimension for Rips (0=H0, 1=H0+H1).")
    return p.parse_args()


def main() -> int:
    args = parse_args()
    cfg = RunConfig()
    cfg.output_root = args.output_dir
    cfg.generators.replicas = int(args.replicas)
    cfg.generators.base_seed = int(args.seed)
    cfg.evaluation.target_col = args.target or cfg.evaluation.target_col
    cfg.evaluation.group_col = args.group_col or cfg.evaluation.group_col
    cfg.evaluation.time_col = args.time_col or cfg.evaluation.time_col
    cfg.evaluation.temporal_split = bool(args.temporal_split)
    cfg.evaluation.sensitive_col = args.sensitive_col or cfg.evaluation.sensitive_col
    if args.quasi_ids:
        cfg.evaluation.quasi_id_cols = [c.strip() for c in args.quasi_ids.split(",") if c.strip()]

    if args.vae_epochs is not None:
        cfg.generators.vae_epochs = int(args.vae_epochs)
    if args.ae_epochs is not None:
        cfg.topology.ae_epochs = int(args.ae_epochs)
    if args.subsample_n is not None:
        cfg.topology.subsample_n = int(args.subsample_n)
    if args.rips_max_dim is not None:
        cfg.topology.rips_max_dim = int(args.rips_max_dim)

    run_root = run_pipeline(cfg, data_path=args.data_path, output_dir=args.output_dir)
    print(f"Run completed. Results written to: {run_root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
